spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**
        - id: feedback-service
          uri: lb://feedback-service
          predicates:
            - Path=/api/v1/feedbacks/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8088
