server:
  port: 8091
  servlet:
    context-path: /api/v1/

spring:
  servlet:
    multipart:
      max-file-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5432/book_tribe
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/book-social-network"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

springdoc:
  default-produces-media-type: application/json

application:
  file:
    uploads:
      photos-output-path: ./uploads

resilience4j:
  circuitbreaker:
    instances:
      feedbackService:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  timelimiter:
    instances:
      feedbackService:
        timeout-duration: 3s
